-- Project Euler
-- Problem 2
--"Even Fibonacci numbers"
-- solved by Max Jackson

-- PROBLEM STATEMENT
-- Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
-- 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
-- By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

-- SOLUTION
-- create the infinite list of fibonacci numbers
fibs = 0 : 1 : zipWith (+) fibs (tail fibs)
-- select the subset of the fibs that are less than 4 million
subsetFibs = takeWhile (<4000000) fibs 
-- find the sum of the even members of the subset
solution = sum [x | x <- subsetFibs, x `mod` 2 == 0]


